name: 'ad_reporting_integration_tests'
version: '0.6.0'
profile: 'integration_tests'
config-version: 2

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
    
vars: 

  google_ads__final_url_performance: "{{ ref('google_ads_final_url_performance_data') }}"
  google_ads__click_performance: "{{ ref('google_ads_click_performance_data') }}"
  google_ads__criteria_performance: "{{ ref('google_ads_criteria_performance_data') }}"
  google_ads__ad_final_url_history: "{{ ref('google_ads_ad_final_url_history_data') }}"
  google_ads__ad_stats: "{{ ref('google_ads_ad_stats_data') }}"
  google_ads__ad_history: "{{ ref('google_ads_ad_history_data') }}"
  google_ads__ad_group_history: "{{ ref('google_ads_ad_group_history_data') }}"
  google_ads__campaign_history: "{{ ref('google_ads_campaign_history_data') }}"
  google_ads__account: "{{ ref('google_ads_account_data') }}"

  microsoft_ads_source:
    account_history: "{{ ref('microsoft_ads_account_history_data') }}"
    ad_group_history: "{{ ref('microsoft_ads_ad_group_history_data') }}"
    ad_history: "{{ ref('microsoft_ads_ad_history_data') }}"
    ad_performance_daily_report: "{{ ref('microsoft_ads_ad_performance_daily_report_data') }}"
    campaign_history: "{{ ref('microsoft_ads_campaign_history_data') }}"
    
  linkedin_source:
    account_history: "{{ ref('linkedin_account_history_data') }}"
    ad_analytics_by_creative: "{{ ref('linkedin_ad_analytics_by_creative_data') }}"
    campaign_group_history: "{{ ref('linkedin_campaign_group_history_data') }}"
    campaign_history: "{{ ref('linkedin_campaign_history_data') }}"
    creative_history: "{{ ref('linkedin_creative_history_data') }}"

  twitter_ads_source:
    account_history: "{{ ref('twitter_account_history_data') }}"
    campaign_history: "{{ ref('twitter_campaign_history_data') }}"
    line_item_history: "{{ ref('twitter_line_item_history_data') }}"
    promoted_tweet_history: "{{ ref('twitter_promoted_tweet_history_data') }}"
    promoted_tweet_report: "{{ ref('twitter_promoted_tweet_report_data') }}"
    tweet_url: "{{ ref('twitter_tweet_url_data') }}"

  pinterest_source:
    ad_group_history: "{{ ref('ad_group_history_data') }}"
    campaign_history: "{{ ref('campaign_history_data') }}"
    pin_promotion_history: "{{ ref('pin_promotion_history_data') }}"
    pin_promotion_report: "{{ ref('pin_promotion_report_data') }}"
    
  facebook_ads_source:
    account_history: "{{ ref('facebook_ads_account_history_data') }}"
    ad_history: "{{ ref('facebook_ads_ad_history_data') }}"
    ad_set_history: "{{ ref('facebook_ads_ad_set_history_data') }}"
    basic_ad: "{{ ref('facebook_ads_basic_ad_data') }}"
    campaign_history: "{{ ref('facebook_ads_campaign_history_data') }}"
    creative_history: "{{ ref('facebook_ads_creative_history_data') }}"

  snapchat_ads_source:
    ad_account_history:  "{{ ref('snapchat_ad_account_history_data') }}"
    ad_history: "{{ ref('snapchat_ad_history_data') }}"
    ad_hourly_report: "{{ ref('snapchat_ad_hourly_report_data') }}"
    ad_squad_history: "{{ ref('snapchat_ad_squad_history_data') }}"
    campaign_history: "{{ ref('snapchat_campaign_history_data') }}"
    creative_history: "{{ ref('snapchat_creative_history_data') }}"
    creative_url_tag_history: "{{ ref('snapchat_creative_url_tag_history_data') }}"

  tiktok_ads_source:
    ad_history: "{{ ref('tiktok_ad_history_data') }}"
    ad_report_hourly: "{{ ref('tiktok_ad_report_hourly_data') }}"
    ad_group_history: "{{ ref('tiktok_adgroup_history_data') }}"
    ad_group_hourly: "{{ ref('tiktok_adgroup_report_hourly_data') }}"
    campaign_history: "{{ ref('tiktok_campaign_history_data') }}"
    campaign_report_hourly: "{{ ref('tiktok_campaign_report_hourly_data') }}"
    advertiser: "{{ ref('tiktok_advertiser_data') }}"

seeds:
  ad_reporting_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"

    ### Microsoft Seeds

    microsoft_ads_ad_group_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    microsoft_ads_ad_performance_daily_report_data:
      +column_types:
        account_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    microsoft_ads_ad_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"

    ### LinkedIn Seeds    
    
    linkedin_creative_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_ad_analytics_by_creative_data:
      +column_types:
        day: timestamp
    linkedin_account_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
    linkedin_campaign_group_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    linkedin_campaign_history_data:
      +column_types:
        created_time: timestamp
        last_modified_time: timestamp
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"

    ### Twitter Seeds

    twitter_tweet_url_data:
      +column_types:
        tweet_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    twitter_promoted_tweet_history_data:
      +column_types:
        tweet_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"

    ### Pinterest Seeds

    ad_group_history_data:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        CAMPAIGN_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    campaign_history_data:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    pin_promotion_history_data:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        AD_GROUP_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        PIN_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    pin_promotion_report_data:
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +column_types:
        PIN_PROMOTION_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        AD_GROUP_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        CAMPAIGN_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ADVERTISER_ID: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"

    ### Google Seeds
    
    google_ads_click_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        criteria_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_criteria_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_final_url_performance_data:
      +column_types:
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        external_customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_stats_data:
      +column_types:
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_campaign_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        customer_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_final_url_history_data:
      +column_types:
        ad_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_group_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    google_ads_ad_history_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        ad_group_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_adgroup_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        base_campaign_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"

    ### Facebook Seeds

    facebook_ads_creative_history_data:
      +column_types:        
        page_link: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
        template_page_link: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_account_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        name: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
    facebook_ads_ad_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ad_set_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        creative_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_ad_set_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_campaign_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_basic_ad_data:
      +column_types:
        ad_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"

    ### Snapchat Seeds

    snapchat_ad_hourly_report_data:
      +column_types:
        date: timestamp